[mypy]
python_version = 3.13
warn_unused_configs = True
show_error_context = True
ignore_missing_imports = False
mypy_path = typings

# No stubs available for these
[mypy-click.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-sqlalchemy]
ignore_missing_imports = True

[mypy-sqlalchemy.types]
ignore_missing_imports = True

[mypy-sqlalchemy.orm]
ignore_missing_imports = True

[mypy-alembic]
ignore_missing_imports = True

[mypy-alembic.config]
ignore_missing_imports = True
