[project]
name = "analysis-daemon"
version = "0.1.0"
description = "A Python-based daemon that periodically checks and schedules tasks from Echolalia"
authors = [
    {name = "Lawrence Borst",email = "laurens.s.borst@gmail.com"},
    {name = "Loann Peurey",email = "loann.peurey@ens.psl.eu"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click (>=8.2.1,<9.0.0)",
    "alembic (>=1.16.4,<2.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "tenacity (>=9.1.2,<10.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
packages = [
    {include = "src"}
]
include = [
    "CONFIG",
    "src/alembic/**",
    "src/alembic.ini"
]


[tool.poetry.scripts]
run-daemon = "src.cli.run_daemon:run_daemon"
run-migrations = "src.cli.run_migrations:run_migrations"
[tool.poetry.group.dev.dependencies]
pytest = "^8.4.1"
pytest-asyncio = "^1.1.0"


[tool.black]
line-length = 88
target-version = ["py313"]


[tool.isort]
profile="black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true