[tox]
requires =
    tox>=4
env_list = py313
skip_missing_interpreters = true

[testenv]
description = run unit tests
deps =
    pytest
    pytest-randomly
commands =
    pytest --strict-markers
commands =
    pytest
