"""add script data to task table

Revision ID: 592821620ffd
Revises: 6f4a55dacffc
Create Date: 2025-11-05 00:57:34.027856

"""

from typing import Sequence, Union

import sqlalchemy as sa

import src.adapters.orm
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "592821620ffd"
down_revision: Union[str, Sequence[str], None] = "6f4a55dacffc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("args", src.adapters.orm.ArgsType(length=256), nullable=True)
    )
    op.add_column(
        "tasks",
        sa.Column("flags", src.adapters.orm.FlagsType(length=256), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "flags")
    op.drop_column("tasks", "args")
    # ### end Alembic commands ###
