"""Replace completed with task_status

Revision ID: 5b5195f089dd
Revises: b789b4d1edf9
Create Date: 2025-08-10 01:14:04.142854

"""

from typing import Sequence, Union

import sqlalchemy as sa

import src.adapters.orm
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b5195f089dd"
down_revision: Union[str, Sequence[str], None] = "b789b4d1edf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "task_status", src.adapters.orm.TaskStatusType(length=256), nullable=False
        ),
    )
    op.execute("UPDATE tasks SET task_status = 'completed' WHERE completed = 1")
    op.execute("UPDATE tasks SET task_status = 'pending' WHERE completed = 0")
    op.drop_column("tasks", "completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("completed", sa.BOOLEAN(), nullable=False))
    op.execute("UPDATE tasks SET completed = 1 WHERE task_status = 'completed'")
    op.execute("UPDATE tasks SET completed = 0 WHERE task_status != 'completed'")
    op.drop_column("tasks", "task_status")
    # ### end Alembic commands ###
