"""remove config table

Revision ID: 5ed6a90fad8f
Revises: 8fcb5e87466b
Create Date: 2025-11-09 22:50:15.083982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ed6a90fad8f"
down_revision: Union[str, Sequence[str], None] = "8fcb5e87466b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("configs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configs",
        sa.Column("version", sa.INTEGER(), nullable=False),
        sa.Column("data", sqlite.JSON(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("version"),
    )
    # ### end Alembic commands ###
