"""add config_version to task table

Revision ID: 6f4a55dacffc
Revises: 8fcb5e87466b
Create Date: 2025-11-03 01:21:10.711094

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f4a55dacffc"
down_revision: Union[str, Sequence[str], None] = "8fcb5e87466b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # NOTE: probably won't work because of the nullable constraint if you
    # have existing configs. But too lazy to write, so early in development,
    # a proper migration that finds the latest config and so on
    # Besides, technically speaking we don't know what config was used by different
    # tasks
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("config_version", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            "fk_tasks_config_version", "configs", ["config_version"], ["version"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_constraint(
            None,  # type: ignore
            "tasks",
            type_="foreignkey",  # type: ignore
        )
        batch_op.drop_column("config_version")
    # ### end Alembic commands ###
