"""remove script_rel_path from task table

Revision ID: 8f5eb32970fd
Revises: d83b25ff49d9
Create Date: 2025-11-02 22:14:58.369762

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f5eb32970fd"
down_revision: Union[str, Sequence[str], None] = "d83b25ff49d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "script_rel_path")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("script_rel_path", sa.VARCHAR(length=256), nullable=True)
    )
    # ### end Alembic commands ###
