"""create initial tables

Revision ID: 922a6ac9d86e
Revises:
Create Date: 2025-08-18 14:18:57.400548

"""

from typing import Sequence, Union

import sqlalchemy as sa

import src.adapters.orm
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "922a6ac9d86e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("task_status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "filesystem_path", src.adapters.orm.PathType(length=256), nullable=False
        ),
        sa.Column(
            "script_rel_path", src.adapters.orm.PathType(length=256), nullable=True
        ),
        sa.Column("model", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
