"""create initial tables

Revision ID: b789b4d1edf9
Revises:
Create Date: 2025-08-05 01:16:08.787692

"""

from typing import Sequence, Union

import sqlalchemy as sa

import src.adapters.orm
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b789b4d1edf9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filesystems",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column(
            "root_abs_path", src.adapters.orm.PathType(length=256), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inputs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("rel_path", src.adapters.orm.PathType(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_tasks",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=256), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_table(
        "outputs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("rel_path", src.adapters.orm.PathType(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "script_tasks",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column(
            "script_file_rel_path",
            src.adapters.orm.PathType(length=256),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("script_tasks")
    op.drop_table("outputs")
    op.drop_table("model_tasks")
    op.drop_table("inputs")
    op.drop_table("tasks")
    op.drop_table("filesystems")
    # ### end Alembic commands ###
